- name: Configuración completa de pfSense mediante SSH y Shell
  hosts: pfsense
  gather_facts: false
  tasks:
    - name: Editar archivo de configuración para configurar interfaces
      ansible.builtin.shell: |
        cp /cf/conf/config.xml /tmp/config_backup.xml
        sed -i '' 's/<wan>/<wan><ipaddr>192.168.0.200<\/ipaddr><subnet>24<\/subnet><gateway>192.168.0.1<\/gateway><\/wan>/' /cf/conf/config.xml
        sed -i '' 's/<lan>/<lan><ipaddr>192.168.1.1<\/ipaddr><subnet>24<\/subnet><\/lan>/' /cf/conf/config.xml
      args:
        executable: /bin/sh

    - name: Aplicar la nueva configuración
      ansible.builtin.shell: |
        pfSsh.php playback apply
      args:
        executable: /bin/sh

    - name: Reiniciar servicios
      ansible.builtin.shell: |
        pfctl -f /cf/conf/config.xml
      args:
        executable: /bin/sh

    - name: Configurar regla de firewall para LAN
      ansible.builtin.shell: |
        echo '
        pass in on vtnet1 from 192.168.1.0/24 to any keep state
        ' > /tmp/lan_rule.txt && pfctl -f /tmp/lan_rule.txt
      args:
        executable: /bin/sh

    - name: Configurar regla de firewall para DMZ
      ansible.builtin.shell: |
        echo '
        pass in on vtnet2 proto tcp from 192.168.2.0/24 to any keep state
        ' > /tmp/dmz_rule.txt && pfctl -f /tmp/dmz_rule.txt
      args:
        executable: /bin/sh

    - name: Configurar regla de firewall para permitir tráfico VPN
      ansible.builtin.shell: |
        echo '
        pass in on vtnet0 proto udp from any to 192.168.0.200 port 51820 keep state
        ' > /tmp/vpn_rule.txt && pfctl -f /tmp/vpn_rule.txt
      args:
        executable: /bin/sh

    - name: Aplicar cambios
      ansible.builtin.shell: |
        pfSsh.php playback apply
      args:
        executable: /bin/sh

    - name: Realizar backup de configuración
      ansible.builtin.shell: |
        cp /cf/conf/config.xml /tmp/pfsense_backup_{{ ansible_date_time.date }}.xml
      register: backup_file

    - name: Guardar archivo de backup localmente
      fetch:
        src: "/tmp/pfsense_backup_{{ ansible_date_time.date }}.xml"
        dest: "/tmp/"
        flat: yes