- name: Configuración completa de pfSense mediante SSH y Shell
  hosts: pfsense
  gather_facts: false
  tasks:
    - name: Crear una copia de seguridad del archivo de configuración actual
      ansible.builtin.shell: |
        cp /cf/conf/config.xml /tmp/config_backup_$(date +%F_%H-%M-%S).xml
      args:
        executable: /bin/sh

    - name: Configurar interfaz WAN en el archivo de configuración
      ansible.builtin.shell: |
        sed -i '' \
        's#<wan>#<wan><ipaddr>192.168.0.200</ipaddr><subnet>24</subnet><gateway>192.168.0.1</gateway></wan>#' \
        /cf/conf/config.xml
      args:
        executable: /bin/sh

    - name: Configurar interfaz LAN en el archivo de configuración
      ansible.builtin.shell: |
        sed -i '' \
        's#<lan>#<lan><ipaddr>192.168.1.1</ipaddr><subnet>24</subnet></lan>#' \
        /cf/conf/config.xml
      args:
        executable: /bin/sh

    - name: Validar cambios realizados en el archivo de configuración
      ansible.builtin.shell: cat /cf/conf/config.xml | grep -E '<ipaddr>|<gateway>'
      args:
        executable: /bin/sh
      register: config_validation

    - name: Mostrar resultado de la validación de configuración
      ansible.builtin.debug:
        msg: "{{ config_validation.stdout }}"

    - name: Aplicar la nueva configuración de pfSense
      ansible.builtin.shell: pfctl -f /cf/conf/config.xml
      args:
        executable: /bin/sh

    - name: Reiniciar el sistema para garantizar la aplicación de cambios
      ansible.builtin.shell: reboot
      args:
        executable: /bin/sh
      ignore_errors: true